- CompanyAdd
- CompanyModify
- CompanyModifyStatus
- CompanyList
- CompanyDetails
- BuySellAdd
- BuySellModify
- BuySellModifyStatus
- BuySellList
- BuySellDetails
- BuySellDelete
- WebChatAdd
- WebChatModify
