- CompanyAdd
- CompanyModify
- CompanyModifyStatus
- CompanyList
- CompanyDetails
- BuySellAdd
- BuySellModify
- BuySellModifyStatus
- BuySellList
- BuySellDetails
- BuySellDelete
- NewsAdd
- NewsDelete
- NewsDetails
- NewsList
- NewsModify
- NewsModifyStatus
- WebChatAdd
- WebChatModify
