class Company < WashOut::Type
  map cpID: :integer,
      cpName: :string,
      cpShortName: :string,
      cpIndustry: :integer,
      cpAddressID: :integer,
      cpAddress: :string,
      cpPost: :integer,
      cpTel: :string,
      cpFax: :string,
      cpSite: :string,
      cpEmail: :string,
      cpAbout: :string,
      cpExtend: :string,
      cpScore: :integer,
      cpType: :string,
      cpOpDate: :string,
      cpUnionEndDate: :string,
      cpState: :string,
      cpMember: :string,
      cpMasterBreed: :string,
      cpMasterProduct: :string,
      cpCorporation: :string,
      cpMode: :string,
      cpPhone: :string,
      cpLogo: :string,
      cpBanner: :string,
      cpAboutPic: :string,
      cpCustomerServiceSmallIcons: :string,
      cpCustomerServiceSmallJS: :string,
      cpCustomerServiceList: :string
end
